l_english:

 iberian: "@fateofiberia_icon! $DLC005_FP2$"
 Norse: "@wrath_icon! $DLC003_FP1$"
 byzantine: "@roadstopower_icon! $DLC014_EP3$"
 iranian: "@legacyofpersia_icon! $DLC010_FP3$"
 nomad: "@khansofthesteppe_icon! $DLC020_CE2$"
 asia: "@allunderheaven_icon! $DLC022_EP4$"
 map_table_style_ce1: "@legendsofthedead_icon! $DLC011_CE1$"
 map_table_style_ep3: "@roadstopower_icon! $DLC014_EP3$"
 map_table_style_tgp: "@allunderheaven_icon! $DLC022_EP4$"
 paper_map_style_tgp: "@allunderheaven_icon! $DLC022_EP4$"
 paper_map_style_yusseter: "@yb_icon! Yusseter's"
